### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by shizpi** [bamlab/react-native-image-header-scroll-view#24]
Is there a way to make the foreground have transparent background?
I want to have a list of cards floating above the header, but my content always have a white background and I haven't found any way to remove it.

**Comment by Nhacsam** [comment]
You mean the content of the scrollView ?
Did you try `childrenStyle={{ backgroundColor: 'trasparent' }}`

**Comment by Nhacsam** [comment]
I added the `scrollViewBackgroundColor` props to change the background color without overriding the style.
https://github.com/bamlab/react-native-image-header-scroll-view/releases/tag/0.8.0
