### ISSUE TITLE
listview

### ISSUE THREAD

**Issue by tianweicc** [bamlab/react-native-image-header-scroll-view#25]
Can you nest listview?

**Comment by Nhacsam** [comment]
You can't nest ScrollView on android. see : https://github.com/facebook/react-native/issues/8024

I added the `ScrollViewComponent` props in the `v0.8.0`. You should be able to use it if you want to use ListView (72e2806). See an example here with Flatlist : https://github.com/bamlab/react-native-image-header-scroll-view-example/blob/master/src/Pages/Avignon.js#L34
