### ISSUE TITLE
ios-TriggeringView nested FlatList

### ISSUE THREAD

**Issue by Webfreshman** [bamlab/react-native-image-header-scroll-view#29]
TriggeringView nested FlatList,Two scrolling conflicts.If you touch FlatList block,your react-native-image-header-scroll-view doesn't work.How to solve it.

**Comment by Nhacsam** [comment]
@Webfreshman Can you give me an example ?

**Comment by Nhacsam** [comment]
@Webfreshman You can't nest ScrollView on android. see : https://github.com/facebook/react-native/issues/8024

I added the `ScrollViewComponent` props in the `v0.8.0`. You should be able to use it if you wat to use FlatList (72e2806). See an example here : https://github.com/bamlab/react-native-image-header-scroll-view-example/blob/master/src/Pages/Avignon.js#L34
