### ISSUE TITLE
Unmet peer dependancy react@16.0.0-alpha.12

### ISSUE THREAD

**Issue by dienast** [bamlab/react-native-image-header-scroll-view#30]
I'm getting an UNMET PEER DEPENDENCY react@16.0.0-alpha.12 during install..

I have:
  "react": "16.0.0-alpha.12",
  "react-native": "^0.47.0",

**Comment by Nhacsam** [comment]
`"react": "16.0.0-alpha.12"` seems to match the requirement `"react": ">=15.3.1"` in the package.json.
Can I see your package.json and the complete log from npm ?
