### ISSUE TITLE
npm out of sync

### ISSUE THREAD

**Issue by GunnarSturla** [bamlab/react-native-image-header-scroll-view#31]
Hello, it appears that the latest version on npm is 0.5.2, which has problems with React 16. I noticed it's been fixed here in the repo in version 0.6.2. Could someone update the package on npm for me?

Thanks in advance!

I also noticed that [ImageHeaderScrollView.js](https://github.com/bamlab/react-native-image-header-scroll-view/blob/master/src/ImageHeaderScrollView.js) is still importing `PropTypes` from `prop-types` even though it's not being used, and is not a dependency in package.json, so it's likely to cause some troubles :)

**Comment by Nhacsam** [comment]
Oops, I published a patch for the `0.5.1` version which was used in one of my project. I guess `npm` used it as default.
It should be fixed now. I published a new version.
