### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by tychota** [bamlab/react-native-image-header-scroll-view#34]
# 1. Put a gif for basic usage

In https://github.com/bamlab/react-native-image-header-scroll-view#basic-usage, there is no gif so the user looks at demo gif which is not related

# 2. Triggering view

When reading the commentary I did not understand what is happening and why this is for.

Maybe a schematic of how the view is used like this:

![image](https://user-images.githubusercontent.com/13785185/36260533-0082778e-1262-11e8-8278-2b044c834f63.png)

and an small sentence about why : "triggering view is a spy view you put on the page that will can call various callback during the scroll" or something like this.

**Comment by Nhacsam** [comment]
Done
