### ISSUE TITLE
和react-navigation的TabNavigator一起使用

### ISSUE THREAD

**Issue by qw110946** [bamlab/react-native-image-header-scroll-view#39]
你好，感谢你制作了这么棒的组件
**问题：**
我想把这项目和`react-navigation`的`TabNavigator`一起使用
**类似效果：**
![debug](https://raw.githubusercontent.com/qw110946/react-native-image-header-scroll-view-with-TabNavigator-debug/master/images/debug1.gif)
**我实现的效果：**
![debug](https://raw.githubusercontent.com/qw110946/react-native-image-header-scroll-view-with-TabNavigator-debug/master/images/debug2.gif)
**具体实现（重现）：**
[链接](https://github.com/qw110946/react-native-image-header-scroll-view-with-TabNavigator-debug)
**想要得到的帮助：**
我的疑问来自于我的实现的TabNavigator不可以向下滑动，希望能告诉我是否可以这样使用

**Comment by Nhacsam** [comment]
Sorry, I don't speak chinese 😥
