### ISSUE TITLE
performance while scrolling - android

### ISSUE THREAD

**Issue by patricktresp** [bamlab/react-native-image-header-scroll-view#4]
Hey, i do have a major performance issue on android while scrolling in header.

Are there any restrictions what content should be after the TriggeringView ?

**Comment by patricktresp** [comment]
So to be more specific:
`<ImageHeaderScrollView
				maxHeight={MAX_HEIGHT}
				minHeight={MIN_HEIGHT}
				maxOverlayOpacity={0}
				minOverlayOpacity={0}
				renderFixedForeground={this.renderFixedForeground}
				renderForeground={this.renderForeground}
				fadeOutForeground={false}

			>
				<View style={{ flex: 1 }}>
					<TriggeringView
						style={{ height: 10, backgroundColor: STYLES.TRANSPARENT }}
						onHide={() => {
							if (this.fixedHeaderReference) {
								this.fixedHeaderReference.fadeInUp(200);
							}
						}}
						onDisplay={() => {
							if (this.fixedHeaderReference) {
								this.fixedHeaderReference.fadeOut(100)
							}
						}}
					>
					</TriggeringView>
					{this.getListView()}

				</View>

			</ImageHeaderScrollView >`

fixedForeGround includes an image with transparency, as does renderForeground ( bit bigger )

It has a major lagging effect on android and works briefly on ios - IF you wait a couple seconds before scrolling.

Are there any restrictions i am missing?

**Comment by Nhacsam** [comment]
No, I think I have a performance issue with `TriggeringView` on android.
I will try to fix it this week :/
Sorry about that.

**Comment by patricktresp** [comment]
ok cool, thanks!

**Comment by Nhacsam** [comment]
I made a new version with some optimization.
Do you still have issues ?

**Comment by timomeh** [comment]
The new version is working _very_ well for me. Very nice. 👍

**Comment by patricktresp** [comment]
Looks better to me, many thanks!

**Comment by Nhacsam** [comment]
Cool :-)
