### ISSUE TITLE
Can you push your Doctor Who demo code ?

### ISSUE THREAD

**Issue by Crael94** [bamlab/react-native-image-header-scroll-view#41]
Hi mate, First of all thank you for this awesome bundle !
Could you put here the code of your Demo GIF please ?
 Thank you ;)

(Merci d'avance :) )

**Comment by Crael94** [comment]
Ok nevermind ... I found it 

https://github.com/bamlab/react-native-image-header-scroll-view-example/blob/3b9d2d0d7f71c6bf877e2d10cc65c9ab7e1b484d/src/Pages/TvShow.js

But I have a question:
How do you make the photo insteed of the header but keep the "arrox-back"

Merci d'avance :)

**Comment by Nhacsam** [comment]
I changed the style of the header to make it transparent and absolute :-)
https://github.com/bamlab/react-native-image-header-scroll-view-example/blob/3b9d2d0d7f71c6bf877e2d10cc65c9ab7e1b484d/src/App.js#L30

**Comment by Dominic-Pace** [comment]
@Nhacsam I'm using the v2 of React Navigation and this doesn't work. Any tips or recommendations? Thanks!

**Comment by raulastrga** [comment]
Hi, I would also like to see the code where you use the button to go back. Thanks

**Comment by Nhacsam** [comment]
With the react-navigation v2, you can use `headerTransparent`
https://github.com/bamlab/react-native-image-header-scroll-view-example/blob/b907324b6c857ff3d287891d8d714060181fd3fd/src/App.js#L37

**Comment by mohsinriaz17** [comment]
i made a snack for that
https://snack.expo.io/@mohsinriaz/react-native-image-header-scroll-view-example

**Comment by kirhim** [comment]
@Nhacsam like @raulastrga mentioned where can I find the code where u used the arrow-back button in the header.
