### ISSUE TITLE
Add placeholder for the header image

### ISSUE THREAD

**Issue by bbeckk** [bamlab/react-native-image-header-scroll-view#43]
I've used a server data to load an image. It shows blank for a moment. How can I add the placeholder image here?

	<HeaderImageScrollView
	headerImage={{uri: ('http://zzz.com/' + this.state.img)}}
	>
		<Text style={styles.title}>The Village Cafe</Text>
		
	</HeaderImageScrollView>

**Comment by Nhacsam** [comment]
Maybe the `renderHeader` props can help you.
