### ISSUE TITLE
Typescript definitions for this library

### ISSUE THREAD

**Issue by rodrigoelp** [bamlab/react-native-image-header-scroll-view#47]
Hi, I was wondering if you guys are interested in type definitions for this library. I would gladly contribute to it as I can see you have some sort of definitions already in the readme file.

**Comment by ivanguimam** [comment]
I'd be happy with that

**Comment by Nhacsam** [comment]
@rodrigoelp @ivanguimam 
I have never done any typescript definition and I didn't use this library in a typescript project yet.

We are moving to typescript in our new project, so will add the definition but I don't know when.

If someone wants to do it and create a pull request, I will be pleased to merge it :-)

**Comment by rodrigoelp** [comment]
Hi guys, I forgot to push or make this public... I've created a PR with the type def (#58). Hopefully it will be all good.

**Comment by rodrigoelp** [comment]
@Nhacsam, good to have you onboard with typescript :)

**Comment by Nhacsam** [comment]
I published it in the 0.10.1 version. Thanks @rodrigoelp
