### ISSUE TITLE
Cannot tap element on renderHeader

### ISSUE THREAD

**Issue by GianMantuan** [bamlab/react-native-image-header-scroll-view#60]
I made a Header using react native-base library to control better the Left and Right position. By doing this, the onPress function inside a Button (again, from native base) doesn't do anything

```
<HeaderScrolLView
    renderHeader={() => (
        <Header>
            <Left>
                <Button onPress={() => this.someFunction(someProps) >
                    <Icon name='arrow-back' />
                </Button>
            </Left>
        </Header>
    )}
>
{ . . . }
</HeaderScrollView>
```

**Comment by Nhacsam** [comment]
I am sorry but it is a known issue. The scrollView is above the header and get the touch.
See https://github.com/bamlab/react-native-image-header-scroll-view/issues/6 fro details
