### ISSUE TITLE
Is it possible to keep the content container having its border radius when the screen is scroll down

### ISSUE THREAD

**Issue by lowzijian** [bamlab/react-native-image-header-scroll-view#70]

**Comment by jefersonjuliani** [comment]
I have the same problem

**Comment by Vasault** [comment]
same issue here

**Comment by Nhacsam** [comment]
Can you send me a screenshot ? I am not sure to understand your issue

**Comment by lowzijian** [comment]
@Nhacsam  
![Capture](https://user-images.githubusercontent.com/40559529/65842966-acaf1900-e361-11e9-8f9b-fc9ac029551b.PNG)

Keeping the border-radius at the top left & right edge of the border while the screen was been scrolled down.

**Comment by kbrandwijk** [comment]
I've solved this by adding a negative top margin identical to my border radius to my main content view.

**Comment by designsheikh** [comment]
> I've solved this by adding a negative top margin identical to my border radius to my main content view.

Can you please show an example of how you have applied this?

Thank you
