### ISSUE TITLE
react native 0.60 Please update the following components: TriggeringView

### ISSUE THREAD

**Issue by georgeMorales** [bamlab/react-native-image-header-scroll-view#78]
With the new versions of react native many methods become obsolete, do you plan to update the library?
Thank you!

**Comment by robertobrogi** [comment]
news about that? thanks

**Comment by Spoutnik97** [comment]
@georgeMorales @robertobrogi I planned to update this lib in a few days

**Comment by sungsong88** [comment]
+1 for this!

**Comment by cristoferrao** [comment]
has this issue been resolved i wanted to use it can you give me a alternative to react-native-image-header-scroll-view

**Comment by sungsong88** [comment]
@cristoferrao This is resolved ATM by introducing `UNSAFE_` to `componentWillMount` and `componentWillReceiveProps` for now. If you pull the master with the latest commit, you won't encounter the warning message anymore.

**Comment by cristoferrao** [comment]
thanks but the warning was removed when i removed the TriggeringView and made hide and that call from HeaderImageScrollView  using on scroll start those options

**Comment by daweido** [comment]
Seems that the version we get when using yarn or npm does not have the TriggeringView changes in it. Is there a way to fix that ?

**Comment by Bang9** [comment]
@Spoutnik97 ping

**Comment by Spoutnik97** [comment]
Thanks for the update 🙂
If you have time you can make a pull request to update it, otherwise I try to do it this week

**Comment by Spoutnik97** [comment]
Done ✅ I updated the package. Please try v1.0.0 and report errors

**Comment by daweido** [comment]
@Spoutnik97 Sorry, didn't have time to create pull request.

Thanks! I'll try it out and report any bugs
