### ISSUE TITLE
Scroll Indicator is buggy.

### ISSUE THREAD

**Issue by dlogvin** [bamlab/react-native-image-header-scroll-view#80]
Hello, have been trying this, but encountered an issue...

![c605cb56eab28e7c73300784d01849e6](https://user-images.githubusercontent.com/62754263/77928520-3019da80-72b1-11ea-8740-6cd84cb2a2b0.png)

I tried using `showsVerticalScrollIndicator={false}` which helped hiding it... but I still believe that thing should be fixed.

**Comment by Jeontaeyun** [comment]
I have same issue with `0.10.1` on `iPhone 11 (iOS 14.0)`
Is there any one having same problem? 

I can't get it why this issue was closing

**Comment by dlogvin** [comment]
> I have same issue with `0.10.1` on `iPhone 11 (iOS 14.0)`
> Is there any one having same problem? 
> 
> I can't get it why this issue was closing

Although it is a bug, you can hide it with `hideVerticalScrollIndicator={true}` or something along those lines.
