### ISSUE TITLE
ListView is deprecated

### ISSUE THREAD

**Issue by tomashornak** [bamlab/react-native-image-header-scroll-view#90]
After updating to
- Expo SDK v39.0.3
- react-native-web 0.13.7

I get following error on web:
```
Failed to compile
.../node_modules/react-native-image-header-scroll-view/src/ImageHeaderScrollView.js
Module not found: Can't resolve 'react-native-web/dist/exports/ListView' in '.../node_modules/react-native-image-header-scroll-view/src'
```

I was able to fix it by removing ListView completely by  from `react-native-image-header-scroll-view/src/ImageHeaderScrollView.js`

**Comment by Spoutnik97** [comment]
I updated the package. Please try v1.0.0 and report errors
